var car = 'subaru';
console.log("Is car == 'subaru'? I predict True");
console.log(car == 'subaru');
var ball = 'blue';
console.log("\n Is ball == 'blue' I predict True");
console.log(ball == 'blue');
var chair = 'broken';
console.log("\n Is chair == 'broken'? I predict True");
console.log(chair == 'broken');
var shirt = 'green';
console.log("\n Is the shirt green? I predict True");
console.log(shirt == 'green');
var bike = 'Honda';
console.log("\n Is that bike a Honda? I predict True");
console.log(bike == 'Honda');
var house = 'small';
console.log("\n Is the house big? I predict False");
console.log(house == 'big');
var laptop = 'slow';
console.log("\n Is the laptop fast? I predict False");
console.log(laptop == 'fast');
var javascript = 'easy';
console.log("\n Is javascript hard? I predict False");
console.log(javascript == 'hard');
var children = 4;
console.log("\n Are there 6 children? I predict False");
console.log(children == 6);
var cars = 3;
console.log("\n Are there 2 cars? I predict False");
console.log(cars == 2);
